name: sync for-next
on:
    push:
        branches:
            - masterx
jobs:
    rebase-for-next:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
              with:
                  ref: for-next
                  fetch-depth: 0
                  token: ${{ secrets.PAT }}
            - run: git fetch origin master
            - run: |
                git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
                git config --local user.name "github-actions[bot]"
                git rebase origin/master
            - run: git push -f
